policy_kw={
    "设备信息":["设备ID", "设备指纹", "设备名称", "IP地址", "ip地址", "设备标识符", "设备标识码", "基站","设备唯一标识符", "DNS", "服务日志", "社交网络信息", "系统版本", "设备信息", "设备相关信息", "设备设置", "软件版本", "应用程序版本", "移动网络信息", "手机样式", "IMEI", "AndroidID", " IDFA", " OPENUDID", " GUID", "OAID", "IMSI", "设备型号", "操作系统","设备名"],
    "位置": ["位置", "GPS", "地址", "定位", "经纬度", "纬度", "基站", "互联网协议地址", "IP地址", "ip地址"],
    "相册": ["相册", "照片", "相片", "视频", "图片"],
    "文件": ["外部存储", "文件", "数据文件", "照片", "相片", "视频", "音频", "图片"],
    "录音": ["麦克风", "录音", "录制"],
    "号码": ["手机号", "手机号码", "电话号码"],
    "相机": ["照相机", "相机", "摄像", "摄像头", "拍摄", "拍照", "照片"],
    "蓝牙":["蓝牙"],
    "网络信息": ["互联网协议地址", "IP地址", "ip地址", "mac地址", "wifi", "Wifi", "WiFi", "WIFI", "Wi-Fi", "WI-FI", "网络类型", "MAC地址", "网络状态", "接入网络", "网络信息", "网络日志", "运营商", "服务提供商", "网络质量数据", "无线网络"],
    "剪贴板": ["剪贴板", "剪切板", "粘贴板", "复制的内容", "粘贴的内容", "拷贝的内容"],
    "生物信息": ["生物识别信息", "脸部图像", "人脸识别","指纹","面容"],
    "传感器":["陀螺仪", "加速计", "加速度", "指南针", "重力感应", "动作感应", "传感器"],
    "NFC":["NFC"],
    "通讯录":["通讯录","联系人"],
    "发票":["发票"],
    
    "手机号": ["电话","手机号","联系方式","联系人号码"],
    "位置": ["地址","地区","位置","门牌号","居住地","小区","地点","社区","街道","楼道","邮编","经纬度","省市区","城市","省份","经度","纬度","所在地","居住证","市","居委","区县","省","乡镇","归属地","目的地","出发地","到达地","住址"],
    "姓名": ["姓名","联系人","收货人"],
    "证件": ["身份证","证件号","卡号","人像面","国徽面","驾驶证","行驶证","营业执照","权证号","医保卡号","就诊卡","健康卡","健康码","航班日期","证书","证件"],
    "健康": ["病情","疾病","体重","身高","血型"],
    "账号密码": ["密码","账号","支付宝账号","支付密码"],
    "组织": ["单位名称","工作单位","学校名称","职业","学号","工号","职位","公司名称","法人","企业","社会信用代码","工作经历","职务"],
    "合同": ["合同"],
    "银行卡": ["银行卡","银行名称","银行账号","开户行","持卡人","信用卡","储蓄卡","银行账户","金融账户"],
    "邮箱": ["邮箱"],
    "发票": ["抬头","税号","发票"],
    "年龄": ["年龄","生日"],
    "航班": ["航班号","登机牌"],
    "婚姻": ["婚姻状况"],
    "教育": ["教育程度","学历","专业"],
    "车辆": ["车辆编号","车牌号","车辆号","车辆信息"],
    "性别": ["性别"],
    "民族": ["民族"],
    "籍贯": ["籍贯","户籍","户口","国籍"],
    "政治": ["政治面貌"],
    "财产": ["财产信息"],
    "简历": [  "简历"],
    "微信运动":["运动数据","微信步数"]
}

collect_kw=["收集","采集","储存","保存","上传"]
deny_kw=["不","不会"]
except_kw0=["除外"]
except_kw1=["除","除了"]
except_kw2=["外","以外","之外"]
disable_kw=["与我们联系","联系地址","注册地址","不可抗力","官网地址"]
text_kw=["不需要","不限于","不熟悉","不稳定","不承担","不开启","链接地址","网站地址","不满意","不公开","不具备","不设立","不从事","不利用","不准确","不正当","不带词","不经通知","不接受","不一致","不记名","不提供","不可逆"]


device_api_privacy = {
    ".getSystemSetting": "设备信息",
    ".getSystemInfo": "设备信息",
    ".getDeviceInfo": "设备信息",
    ".showShareImageMenu": "文件",
    ".shareVideoMessage": "文件",
    ".shareFileMessage": "文件",
    ".uploadFile": "文件",
    ".startLocalServiceDiscovery": "设备信息",
    ".createMapContext.*?.fromScreenLocation": "位置",
    ".createMapContext.*?.getCenterLocation": "位置",
    ".createMapContext.*?.toScreenLocation": "位置",
    ".chooseMessageFile": "文件",
    ".chooseImage": "相册",
    ".chooseVideo": "相册",
    ".chooseMedia": "相册",
    ".createLivePusherContext.*?.snapshot": "图片",
    ".createLivePusherContext.*?.sendMessage": "文件",
    ".createLivePusherContext.*?.startPreview": "相机",
    ".createLivePusherContext.*?.switchCamera": "相机",
    ".startRecord": "录音",
    ".getRecorderManager": "录音",
    ".createCameraContext.*?.onCameraFrame": "相机",
    ".createCameraContext.*?.startRecord": "相机",
    ".createCameraContext.*?.takePhoto": "相机",
    "CameraFrameListener.start": "相机",
    ".subscribeVoIPVideoMembers": "相机, 录音",
    ".setEnable1v1Chat": "录音",
    ".onVoIPVideoMembersChanged": "相机, 录音",
    ".joinVoIPChat": "录音",
    ".join1v1Chat": "录音",
    ".startLocationUpdateBackground": "位置",
    ".startLocationUpdate": "位置",
    ".openLocation": "位置",
    ".onLocationChange": "位置",
    ".getLocation": "位置",
    ".choosePoi": "位置",
    ".chooseLocation": "位置",
    ".openDocument": "文件",
    ".getSavedFileList": "文件",
    ".getSavedFileInfo": "文件",
    ".getFileSystemManager.*?.getFileInfo": "文件",
    ".getFileSystemManager.*?.getSavedFileList": "文件",
    ".getFileSystemManager.*?.readCompressedFile": "文件",
    ".getFileSystemManager.*?.readFile": "文件",
    ".chooseInvoiceTitle": "发票",
    ".chooseInvoice": "发票",
    ".startSoterAuthentication": "生物信息",
    ".checkIsSupportSoterAuthentication": "生物信息",
    ".checkIsSoterEnrolledInDevice": "生物信息",
    ".startBluetoothDevicesDiscovery": "蓝牙",
    ".openBluetoothAdapter": "蓝牙",
    ".onBluetoothDeviceFound": "蓝牙",
    ".onBluetoothAdapterStateChange": "蓝牙",
    ".makeBluetoothPair": "蓝牙",
    ".isBluetoothDevicePaired": "蓝牙",
    ".getConnectedBluetoothDevices": "蓝牙",
    ".getBluetoothDevices": "蓝牙",
    ".getBluetoothAdapterState": "蓝牙",
    ".writeBLECharacteristicValue": "蓝牙",
    ".readBLECharacteristicValue": "蓝牙",
    ".onBLEConnectionStateChange": "蓝牙",
    ".getBLEDeviceServices": "蓝牙",
    ".getBLEDeviceRSSI": "蓝牙",
    ".getBLEDeviceCharacteristics": "蓝牙",
    ".createBLEConnection": "蓝牙",
    ".onBLEPeripheralConnectionStateChanged": "蓝牙",
    ".createBLEPeripheralServer.*?.onCharacteristicReadRequest": "蓝牙",
    ".createBLEPeripheralServer.*?.startAdvertising": "蓝牙",
    ".createBLEPeripheralServer.*?.writeCharacteristicValue": "蓝牙",
    ".startBeaconDiscovery": "蓝牙",
    ".onBeaconUpdate": "蓝牙",
    ".onBeaconServiceChange": "蓝牙",
    ".getBeacons": "蓝牙",
    ".getNFCAdapter": "NFC",
    ".getIsoDep": "NFC",
    ".getMifareClassic": "NFC",
    ".getMifareUltralight": "NFC",
    ".getNdef": "NFC",
    ".getNfcA": "NFC",
    ".getNfcB": "NFC",
    ".getNfcF": "NFC",
    ".getNfcV": "NFC",
    ".startWifi": "Wifi",
    ".setWifiList": "Wifi",
    ".onWifiConnected": "Wifi",
    ".onGetWifiList": "Wifi",
    ".getWifiList": "Wifi",
    ".getConnectedWifi": "Wifi",
    ".connectWifi": "Wifi",
    ".chooseContact": "通讯录",
    ".getBatteryInfo": "设备信息",
    ".setClipboardData": "剪贴板",
    ".getClipboardData": "剪贴板",
    ".startHCE": "NFC",
    ".sendHCEMessage": "NFC",
    ".onHCEMessage": "NFC",
    ".getHCEState": "NFC",
    ".onNetworkWeakChange": "网络信息",
    ".onNetworkStatusChange": "网络信息",
    ".getNetworkType": "网络信息",
    ".getLocalIPAddress": "网络信息",
    ".getScreenBrightness": "设备信息",
    ".startAccelerometer": "传感器",
    ".onAccelerometerChange": "传感器",
    ".startCompass": "传感器",
    ".onCompassChange": "传感器",
    ".startDeviceMotionListening": "传感器",
    ".onDeviceMotionChange": "传感器",
    ".startGyroscope": "传感器",
    ".onGyroscopeChange": "传感器",
    ".scanCode": "相机",
    ".createVKSession.*?.getVKFrame": "相机",
    ".createVKSession.*?.start": "相机",
    ".initFaceDetect": "生物信息",
    ".faceDetect": "生物信息"
}


plt_api_privacy = {
    ".chooseAddress": "地址",
    ".chooseInvoiceTitle": "发票",
    ".chooseInvoice": "发票",
    "scope.werun": "微信运动",
    ".getWeRunData": "微信运动",
    "\"getPhoneNumber\"": "手机号",
    ".chooseLicensePlate": "车牌"
}

input_kwd_privacy = {
    "电话": "手机号",
    "地址": "位置",
    "地区": "位置",
    "姓名": "姓名",
    "手机号": "手机号",
    "身份证": "证件",
    "病情": "健康",
    "密码": "账号密码",
    "单位名称": "组织",
    "合同": "重要文件",
    "银行卡": "银行卡",
    "疾病": "健康",
    "位置": "位置",
    "邮箱": "邮箱",
    "抬头": "发票",
    "税号": "发票",
    "银行名称": "银行卡",
    "银行账号": "银行卡",
    "门牌号": "位置",
    "账号": "账号密码",
    "工作单位": "组织",
    "居住地": "位置",
    "学校名称": "组织",
    "小区": "位置",
    "地点": "位置",
    "年龄": "年龄",
    "证件号": "证件",
    "社区": "位置",
    "街道": "位置",
    "楼道": "位置",
    "卡号": "证件",
    "联系方式": "手机号",
    "联系人号码": "手机号",
    "航班号": "航班",
    "邮编": "位置",
    "婚姻状况": "婚姻",
    "教育程度": "教育",
    "经纬度": "位置",
    "开户行": "银行卡",
    "持卡人": "银行卡",
    "支付宝账号": "账号密码",
    "联系人": "姓名",
    "省市区": "位置",
    "职业": "组织",
    "人像面": "证件",
    "国徽面": "证件",
    "城市": "位置",
    "车辆编号": "车辆",
    "支付密码": "账号密码",
    "省份": "位置",
    "学号": "组织",
    "性别": "性别",
    "设备名": "设备信息",
    "工号": "组织",
    "经度": "位置",
    "纬度": "位置",
    "驾驶证": "证件",
    "行驶证": "证件",
    "车牌号": "车辆",
    "民族": "民族",
    "生日": "年龄",
    "营业执照": "证件",
    "所在地": "位置",
    "居住证": "位置",
    "职位": "组织",
    "公司名称": "组织",
    "发票": "发票",
    "权证号": "证件",
    "车辆号": "车辆",
    "医保卡号": "证件",
    "籍贯": "籍贯",
    "就诊卡": "证件",
    "法人": "组织",
    "企业": "组织",
    "社会信用代码": "组织",
    "市": "位置",
    "居委": "位置",
    "区县": "位置",
    "省": "位置",
    "乡镇": "位置",
    "户籍": "籍贯",
    "国家": "位置",
    "户口": "籍贯",
    "学历": "教育",
    "健康卡": "证件",
    "健康码": "证件",
    "信用卡": "银行卡",
    "登机牌": "航班",
    "储蓄卡": "银行卡",
    "航班日期": "证件",
    "收货人": "姓名",
    "归属地": "位置",
    "目的地": "位置",
    "出发地": "位置",
    "到达地": "位置",
    "车辆信息": "车辆",
    "银行账户": "银行卡",
    "金融账户": "银行卡",
    "住址": "位置",
    "工作经历": "组织",
    "职务": "组织",
    "国籍": "籍贯",
    "政治面貌": "政治",
    "体重": "健康",
    "证书": "证件",
    "专业": "教育",
    "财产信息": "财产",
    "身高": "健康",
    "简历": "简历"
}

privacy_En = {
    "设备信息": "device information",
    "相册": "photographic image",
    "文件": "file",
    "位置/地址": "location information",
    "截图/screen": "screenshot",
    "相机": "camera",
    "录音": "recording",
    "生物信息": "biometric information",
    "蓝牙": "bluetooth",
    "NFC": "NFC",
    "剪贴板": "clipboard data",
    "网络信息": "network information",
    "打电话": "calling information",
    "传感器": "sensor data",
    "手机号/通讯录": "contact information",
    "发票": "property information",
    "微信运动": "activity information",
    "车牌号/车辆": "driving information",
    "姓名": "name",
    "证件": "identity information",
    "健康": "physiological and health information",
    "账号密码": "online identity information",
    "组织": "education and career information",
    "重要文件": "file",
    "银行卡": "property information",
    "邮箱": "contact information",
    "年龄": "age",
    "交通信息": "activity information",
    "婚姻": "marriage situation",
    "教育": "education and career information",
    "性别": "gender",
    "民族": "ethnic group",
    "籍贯": "nationality",
    "政治": "political or religious views",
    "财产": "property information",
    "简历": "education and career information",
    "合同": "file",
    "航班": "activity information",
    "号码": "contact information",
    "车牌": "driving information",
    "证件号": "identity information",
    "联系方式": "contact information",
    "Wifi": "network information"
}

default_cmps = {
    "cover-image", "cover-view", "match-media", "movable-area", "movable-view", "page-container", "root-portal", "scroll-view", "share-element", "swiper", "swiper-item", "view", "icon", "progress", "rich-text", "text", "button", "checkbox", "checkbox-group", "editor", "form", "input", "keyboard-accessory", "label", "picker", "picker-view", "picker-view-column", "radio", "radio-group", "slider", "switch", "textarea", "functional-page-navigator", "navigator", "audio", "camera", "image", "live-player", "live-pusher", "video", "voip-room", "map", "canvas", "web-view", "ad", "ad-custom", "official-account", "open-data", "native-component", "aria-component", "navigation-bar", "page-meta", "slot", "block"
}

components_kwd = set(["checkbox", "input", "editor", "picker", "radio", "textarea", "slider", "switch"])


inputP = list(input_kwd_privacy.keys())
